version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "80:3000"
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongodb  

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

