version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "80:3000"
    depends_on:
      - server

  server:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production