apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-demo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rancher-demo
  template:
    metadata:
      labels:
        app: rancher-demo
    spec:
      containers:
      - name: rancher-demo-container
        image: saffar29/client:latest   # Remplacez ceci par l'image Docker de votre application
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rancher-demo-service
spec:
  selector:
    app: rancher-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Changez cela en ClusterIP si vous n'avez pas besoin d'un accès externe
